name: Docker Image CI

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on:
      group: prod
    steps:
    - uses: actions/checkout@v3
    - name: set branch variable
      id: branch
      run: |
        if [ "$GITHUB_EVENT_NAME" == "delete" ]; then
          BRANCH=${{ github.event.ref }}
        else
          BRANCH=${{ github.base_ref || github.ref_name }}
        fi
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    - name: set tags
      run: |
        if [ "$BRANCH" == "main" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          echo "DOCKER_POSTFIX=_dev" >> $GITHUB_ENV
        fi
        IMAGE_NAME=$(cat Dockerfile | grep "ENV IMAGE_NAME " | cut -d " " -f3)
        IMAGE_VERSION=$(cat Dockerfile | grep "ENV IMAGE_VERSION " | cut -d " " -f3)
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
    - name: set credentials
      env:
        DOCKERIO_USERNAME_DEV: ${{ secrets.DOCKERIO_USERNAME_DEV }}
        DOCKERIO_TOKEN_DEV: ${{ secrets.DOCKERIO_TOKEN_DEV }}
        DOCKERIO_USERNAME_PROD: ${{ secrets.DOCKERIO_USERNAME_PROD }}
        DOCKERIO_TOKEN_PROD: ${{ secrets.DOCKERIO_TOKEN_PROD }}
      run: |
        if [ "$BRANCH" == "main" ]; then
          echo "DOCKER_USERNAME=$DOCKERIO_USERNAME_DEV" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=$DOCKERIO_TOKEN_DEV" >> $GITHUB_ENV
        else
          echo "DOCKER_USERNAME=$DOCKERIO_USERNAME_PROD" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=$DOCKERIO_TOKEN_PROD" >> $GITHUB_ENV
        fi
        echo "REPO_ADDR=docker.io" >> $GITHUB_ENV
    - name: Login to repository
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REPO_ADDR }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        DATESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag ${REPO_ADDR}/qumulus/${IMAGE_NAME}:${DATESTAMP}
        docker tag ${REPO_ADDR}/qumulus/${IMAGE_NAME}:${DATESTAMP} ${REPO_ADDR}/qumulus/${IMAGE_NAME}:v${IMAGE_VERSION}${DOCKER_POSTFIX}
        docker push ${REPO_ADDR}/qumulus/${IMAGE_NAME} --all-tags
