name: Docker Image CI

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on:
      group: prod
    steps:
    - uses: actions/checkout@v3
    - name: set branch variable
      id: branch
      run: |
        if [ "$GITHUB_EVENT_NAME" == "delete" ]; then
          BRANCH=${{ github.event.ref }}
        else
          BRANCH=${{ github.base_ref || github.ref_name }}
        fi
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    - name: set tags
      run: |
        if [ "$BRANCH" == "main" ]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          echo "DOCKER_POSTFIX=_dev" >> $GITHUB_ENV
        fi
        IMAGE_NAME=$(cat Dockerfile | grep "ENV IMAGE_NAME " | cut -d " " -f3)
        IMAGE_VERSION=$(cat Dockerfile | grep "ENV IMAGE_VERSION " | cut -d " " -f3)
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

    - name: Set Harbor Environment Variables
      env:
        HARBOR_TOKEN_PROD: ${{ secrets.HARBOR_TOKEN_PROD }}
        HARBOR_ADDR_PROD: "repo.qumulus.io"
        HARBOR_TOKEN_DEV: ${{ secrets.HARBOR_TOKEN_DEV }}
        HARBOR_ADDR_DEV: "repo.qumulus.dev"
      run: |
        if [ "${{ github.base_ref || github.ref_name }}" == "main" ]; then
          echo "HARBOR_TOKEN=$HARBOR_TOKEN_PROD" >> $GITHUB_ENV
          echo "HARBOR_ADDR=$HARBOR_ADDR_PROD" >> $GITHUB_ENV
        else
          echo "HARBOR_TOKEN=$HARBOR_TOKEN_DEV" >> $GITHUB_ENV
          echo "HARBOR_ADDR=$HARBOR_ADDR_DEV" >> $GITHUB_ENV
        fi
        echo "HARBOR_USERNAME=robot\$github" >> $GITHUB_ENV

    - name: Login to Harbor Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.HARBOR_ADDR }}
        username: ${{ env.HARBOR_USERNAME }}
        password: ${{ env.HARBOR_TOKEN }}

    - name: Build the Docker image
      run: |
        DATESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag ${HARBOR_ADDR}/qcp-images/${IMAGE_NAME}:${DATESTAMP}
        docker tag ${HARBOR_ADDR}/qcp-images/${IMAGE_NAME}:${DATESTAMP} ${HARBOR_ADDR}/qcp-images/${IMAGE_NAME}:v${IMAGE_VERSION}${DOCKER_POSTFIX}
        docker push ${HARBOR_ADDR}/qcp-images/${IMAGE_NAME} --all-tags
